### ISSUE TITLE
IPFS 0.5 release

### ISSUE THREAD

**Issue by akru** [airalab/aira#102]
New IPFS released: https://github.com/ipfs/go-ipfs/releases/tag/v0.5.0

Check support before upgrade AIRA:

* [ ] Robonomics JS
* [x] robonomics_comm
* [x] XRTd

Most important changes:

* Storage format changed
* Address format changed (/ip4/193.45.1.24/tcp/4001/ipfs/QmSomePeerID to /ip4/193.45.1.24/tcp/4001/p2p/QmSomePeerID)
* AutoNAT
* Support ENS using https://eth.link/
* Gossipsub as default PubSub protocol

**Comment by akru** [comment]
XRTd pubsub module implemented as shell streams. Should have no problems.
https://github.com/airalab/robonomics-tools/blob/master/src/Network/Ipfs/PubSub.hs

**Comment by Vourhey** [comment]
robonomics_comm + ipfs 0.5.0 doesn't work

ipfs-api 0.4.4
ipfshttpclient 0.4.13
```
[INFO] [1588239408.006708]: Build IPFS client: http://127.0.0.1:5001
[INFO] [1588239408.099230]: Build IPFS client: http://127.0.0.1:5001
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/http.py", line 266, in _do_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://127.0.0.1:5001/api/v0/version?stream-channels=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/osboxes/ros_ws/src/robonomics_comm/ipfs_common/scripts/ipfs_channel_node", line 7, in <module>
    ipfs_channel_node()
  File "/home/osboxes/ros_ws/src/robonomics_comm/ipfs_common/src/ipfs_common/nodes.py", line 6, in ipfs_channel_node
    IPFSChannel().spin()
  File "/home/osboxes/ros_ws/src/robonomics_comm/ipfs_common/src/ipfs_common/ipfs_channel.py", line 24, in __init__
    self.ipfs_pubsub_client = build_client(self.ipfs_http_provider)
  File "/home/osboxes/ros_ws/src/robonomics_comm/ipfs_common/src/ipfs_common/ipfs_common.py", line 21, in build_client
    session=True, timeout=no_read_timeout)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/client/__init__.py", line 101, in connect
    version_str = client.version()["Version"]
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/client/base.py", line 15, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/client/miscellaneous.py", line 204, in version
    return self._client.request('/version', decoder='json', **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/http.py", line 51, in wrapper
    return func(self, *args, **merged)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/http.py", line 386, in request
    username, password, data, timeout)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/http.py", line 307, in _request
    self._do_raise_for_status(res)
  File "/usr/local/lib/python3.6/dist-packages/ipfshttpclient/http.py", line 286, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://127.0.0.1:5001/api/v0/version?stream-channels=true
```

**Comment by akru** [comment]
@Vourhey what's about reporting to IPFS client libraries repo?

**Comment by Vourhey** [comment]
https://github.com/airalab/airapkgs/commit/0432390ac9844c88646ba6f6955f6baec97789b9

Updated client library to the latest. Now it works

**Comment by akru** [comment]
@vol4tim is js part works well with ipfs 0.5?

**Comment by vol4tim** [comment]
Да, все работает.
