### ISSUE TITLE
catkin fails to build

### ISSUE THREAD

**Issue by nschoe** [airalab/aira#67]
Hi, I have cloned `airapkgs` and I have narrowed an issue with `catkin`. Here is a minimal `shell.nix`:

```
with import /home/nschoe/airapkgs {};

stdenv.mkDerivation {
    name = "test-aira-env";
    buildInputs = [ catkin
                  ];
    shellHook = ''
        printf "Test"
    '';
}
```

and here's the output when I try to enter the shell with `nix-shell`:

```
[nix-shell:~/build/aira]$ nix-shell 
these derivations will be built:
  /nix/store/m285wp2zza5p4nsn3km6y6xdzp8arw1n-catkin-0.7.11.drv
building '/nix/store/m285wp2zza5p4nsn3km6y6xdzp8arw1n-catkin-0.7.11.drv'...
unpacking sources
unpacking source archive /nix/store/sh29ii3gbswhkgsy24s8dv8wnvm71wvr-source
source root is source
patching sources
configuring
fixing cmake files...
cmake flags: -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/m71xl0jjv1kax8zpk4fr6qsj89f5kk2d-catkin-0.7.11/include -DCMAKE_INSTALL_LIBDIR=/nix/store/m71xl0jjv1kax8zpk4fr6qsj89f5kk2d-catkin-0.7.11/lib -DCMAKE_INSTALL_NAME_DIR=/nix/store/m71xl0jjv1kax8zpk4fr6qsj89f5kk2d-catkin-0.7.11/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_DEPLOYMENT_TARGET= -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=last -DCMAKE_STRIP=/nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip -DCMAKE_RANLIB=/nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/ranlib -DCMAKE_AR=/nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/m71xl0jjv1kax8zpk4fr6qsj89f5kk2d-catkin-0.7.11 -DCATKIN_ENABLE_TESTING=OFF -DSETUPTOOLS_DEB_LAYOUT=OFF
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0/bin/gcc
-- Check for working C compiler: /nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0/bin/g++
-- Check for working CXX compiler: /nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /build/source/build/devel
-- Using CMAKE_PREFIX_PATH: /nix/store/2x6iv4zw7d3if9i549kaw0y91g8d39iy-patchelf-0.9;/nix/store/wvz8gp7bhwp572jy2w1n48n1rn8wdrw3-paxctl-0.9;/nix/store/10yq7kwlvbc6h658izmrlsspry1g9f3c-gcc-wrapper-7.3.0;/nix/store/an3icm1hajqx1lld6n8q4qr40nwbs544-binutils-wrapper-2.30;/nix/store/8jvmf9idk3zhfr9amwif4ggr5nrwnykp-cmake-3.12.1;/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6;/nix/store/bsga2zrxh8nrd76j3ixv7yqi5h8bwa7k-empy-3.3.2;/nix/store/p5r0kmkg9ig3j7b5wm7943xdq06wqz99-python3.6-setuptools-40.2.0;/nix/store/n1hblbwi0q0zma4x9vyrpjp34138wm0l-python3.6-catkin_pkg-0.4.1;/nix/store/5cbgxba09hb9kqbsdfjplmlpyakp202z-python3.6-pyparsing-2.2.0;/nix/store/bh3ksb9fkqk7lmchqap55ib6ghjbk6mv-python3.6-docutils-0.14;/nix/store/7mnv7afxsihq63fcl3vzdw5zy2qxf7kd-python3.6-python-dateutil-2.7.3;/nix/store/k2jn42dj98rnf7zwvwdb006kyh91s00n-python3.6-six-1.11.0;/nix/store/j13wc33hjgi032njrvsmy80jmmvl7g7w-python3.6-setuptools_scm-3.1.0;/nix/store/9gpnix1m9px86fbgvi1z4zcknc30x3m4-python3.6-rospkg-1.1.4;/nix/store/nymmamqzklv6c5y3n5qr7z5b66lzylmk-python3.6-PyYAML-3.13;/nix/store/qp7ndk8s2jpcn3lj7lipvyr88517z616-libyaml-0.2.1
-- Found PythonInterp: /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/bin/python (found version "3.6.6")
-- Using PYTHON_EXECUTABLE: /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/bin/python
-- Using default Python package layout
-- Found PY_em: /nix/store/bsga2zrxh8nrd76j3ixv7yqi5h8bwa7k-empy-3.3.2/lib/python3.6/site-packages/em.py
-- Using empy: /nix/store/bsga2zrxh8nrd76j3ixv7yqi5h8bwa7k-empy-3.3.2/lib/python3.6/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: OFF
-- catkin 0.7.11
Traceback (most recent call last):
  File "/build/source/build/catkin_generated/generate_cached_setup.py", line 22, in <module>
    code = generate_environment_script('/build/source/build/devel/env.sh')
  File "/build/source/cmake/../python/catkin/environment_cache.py", line 61, in generate_environment_script
    output = subprocess.check_output([env_script, sys.executable, '-c', python_code])
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/build/source/build/devel/env.sh': '/build/source/build/devel/env.sh'
CMake Error at cmake/safe_execute_process.cmake:11 (message):

  execute_process(/nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/bin/python
  "/build/source/build/catkin_generated/generate_cached_setup.py") returned
  error code 1
Call Stack (most recent call first):
  cmake/all.cmake:186 (safe_execute_process)
  CMakeLists.txt:8 (include)


-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
builder for '/nix/store/m285wp2zza5p4nsn3km6y6xdzp8arw1n-catkin-0.7.11.drv' failed with exit code 1
error: build of '/nix/store/m285wp2zza5p4nsn3km6y6xdzp8arw1n-catkin-0.7.11.drv' failed
```

Note the issue build file `/build/source/build/devel/env.sh` not being found. It used to work, but now it fails. I'm not sure what's wrong.

**Comment by akru** [comment]
Hi! Thank you for reporting!

Unfortunately current `catkin` port does not support building in sandbox, could you try to disable sandbox at /etc/nixos/configuration.nix:

```nix
{
  nix.useSandbox = false;
}
```

**Comment by nschoe** [comment]
Thanks for answering @akru !

So I tried your fix: I edited my `configuration.nix`, tested it with `sudo nixos-rebuild test` and tried entering the `nix-shell` again.
It... worked o_O.

So first of all, thanks for that :)

But I'm actually surprised because I have been using `airapkgs` for several months now, to develop a ROS package, and I have been using this `shell.nix` (again: for several months):

```
let pkgs = import /home/nschoe/nixpkgs {};
    airapkgs = import /home/nschoe/airapkgs {};
in
airapkgs.stdenv.mkDerivation {
  name = "papyrus-kheops-env";
  buildInputs = [ airapkgs.libGL
                  airapkgs.qtcreator
                  airapkgs.qt5.full
                  airapkgs.qt5.qtbase
                  airapkgs.qt5.qtsvg
                  airapkgs.qt5.qtcharts
                  airapkgs.cmake
                  airapkgs.boost167
                  airapkgs.eigen3_3
                  airapkgs.libuuid
                  airapkgs.cryptopp
                  airapkgs.valgrind
                  airapkgs.linuxHeaders
                  airapkgs.opensans-ttf
                  airapkgs.ros_comm
                  airapkgs.joy
                  airapkgs.nav_msgs
                  airapkgs.tf
                  airapkgs.diagnostic_msgs
                ];

  shellHook = ''
        # printf "Sourcing ROS's setup.bash..."
        # source ${airapkgs.ros_comm}/setup.bash
        # echo "done!"

        # printf "Sourcing joy's setup.bash..."
        # source ${airapkgs.joy}/setup.bash
        # echo "done!"

        # printf "Sourcing tf's setup.bash..."
        # source ${airapkgs.tf}/setup.bash
        # echo "done!"

        # printf "Sourcing nav_msgs's setup.bash..."
        # source ${airapkgs.nav_msgs}/setup.bash
        # echo "done!"

        # printf "Sourcing diagostic_msgs's setup.bash..."
        # source ${airapkgs.diagnostic_msgs}/setup.bash
        # echo "done!"

        printf "Sourcing catkin workspace's setup.bash..."
        source ../../devel/setup.bash
        echo "done!"
  '';
}

```

(Yeah, I know the nschoe/nixpkgs is not used anymore, I have a refined version of the file, without it. Also lots of comments in the shellHook section because I cannot understand what to source / not source).

Anyway the bottom line is that it worked for several months (and I had not disabled sandbox in `configuration/nix`) but very recently this shell.nix file refused to build, hence my issue.

Do you have any idea why it suddenly doesn't work? Is there anything that might have changed it?

Thanks again for your answer and your time.

**Comment by akru** [comment]
Previously you use nix cache from hydra.aira.life, right? You can touch troubles with build only if you try to build catkin locally. From cache it should get correct with and without sandboxing.

**Comment by nschoe** [comment]
Sorry for the delay, I skiped the email.
Hum, no I have never set up aira's build cache (I don't event know how to do it), so I don't think this is it.
This is weird that it used to work, then.

I disabled sandboxing and now it works, as you predicted. But is there any chance I can disable it locally, for the `nix-shell` only or do I have to disable it globally for my whole configuration.nix?

**Comment by akru** [comment]
Unfortunatelly, as I see, `catkin` use `/usr/bin/env` in many places and can't build in sandbox now. I don't know is possible to disable sandbox locally for one package or not. May be something like `override` will be helpful.

Currently I create an issue https://github.com/airalab/aira/issues/68 as enhancement for airapkgs and close this. Thank you for your work!

**Comment by akru** [comment]
Of course, thank you for your help. I'll publish more information to https://github.com/airalab/aira/issues/68. Working around issues is preferred to me.
