### ISSUE TITLE
ROS is broken

### ISSUE THREAD

**Issue by nschoe** [airalab/aira#74]
I don't know which recent commit or merge did it, but I have `git pull` on the `nixos-unstable` branch.

So on commit 1cc96e8a6c8, here is what I do:

```
$> nix-shell -I nixpkgs=/home/nschoe/airapkgs -p ros_comm
[snip]

[nix-shell]$ echo $buildInput
/nix/store/pmizhrcq370xb9ipcv9pd4q8q7a4i079-ros_comm-1.14.4
[nix-shell] source /nix/store/pmizhrcq370xb9ipcv9pd4q8q7a4i079-ros_comm-1.14.4/setup.bash

[nix-shell]$ roscore
WARNING: unable to configure logging. No log files will be generated
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: roslaunch
ROS path [0]=/nix/store/35ndffzbkxvapnyf733zc12b0g6c8kl5-rosbuild-1.14.4/share/ros
The traceback for the exception was written to the log file
Traceback (most recent call last):
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/__init__.py", line 322, in main
    p.start()
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/parent.py", line 277, in start
    self._start_infrastructure()
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/parent.py", line 226, in _start_infrastructure
    self._load_config()
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/parent.py", line 138, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/config.py", line 447, in load_config_default
    load_roscore(loader, config, verbose=verbose)
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/config.py", line 92, in load_roscore
    f_roscore = get_roscore_filename()
  File "/nix/store/6akbq97ppr18ak4aq12kiap15r45w3km-roslaunch-1.14.4/lib/python3.6/site-packages/roslaunch/config.py", line 84, in get_roscore_filename
    return os.path.join(r.get_path('roslaunch'), 'resources', 'roscore.xml')
  File "/nix/store/w7nx3caffpbbp1xyawz77ry1brb9440d-python3.6-rospkg-1.1.7/lib/python3.6/site-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roslaunch
ROS path [0]=/nix/store/35ndffzbkxvapnyf733zc12b0g6c8kl5-rosbuild-1.14.4/share/ros
```

This works fine on commit 2c37a3c3a2a557e496 (this is an older commit, I just happened to have a branch on this commit, so I could test).
I'll try using `git bisect` to try and find which commit broke in between.

Note that on commit 2c37a3c3a2a557e496, `ros_comm` is on version `1.13.6` (on latest commit it's `1.14.4`).

**Comment by nschoe** [comment]
I found the first bad commit: c4cd2ba862e7625eafc520058cace599d55f32be according to my tests with `git bisect`.

I'll try to `git pull` and see if this is works.
Thanks for your reactivity.

**Comment by nschoe** [comment]
@akru I confirm this works on the latest commit (43501972230).
Thanks. I'm closing because issue seems to be solved :)
